DROP TABLE IF EXISTS DOCTORS;
DROP TABLE IF EXISTS APPOINTMENTS;

CREATE TABLE DOCTORS(
  ID INT PRIMARY KEY NOT NULL,
  FIRST_NAME TEXT,
  LAST_NAME TEXT
);

CREATE TABLE APPOINTMENTS(
  ID INT PRIMARY KEY NOT NULL,
  PATIENT_FIRST_NAME TEXT,
  PATIENT_LAST_NAME TEXT,
  DATE TEXT,
  TIME TIME,
  KIND TEXT,
  DOCTOR_ID INT
);

INSERT INTO DOCTORS VALUES(1,'TREVOR','NAN');
INSERT INTO DOCTORS VALUES(2,'ANGELA','SMITH');

INSERT INTO APPOINTMENTS VALUES(1,'Sterling','Archer','2022-06-22','T08:00:00','new patient',1);
INSERT INTO APPOINTMENTS VALUES(2,'Cyril','Figis','2022-06-22','T08:30:00','follow-up',1);
INSERT INTO APPOINTMENTS VALUES(3,'Ray','Gilette','2022-06-22','T09:00:00','follow-up',1);
INSERT INTO APPOINTMENTS VALUES(4,'Lana','Kane','2022-06-22','T09:30:00','new Patient',1);
INSERT INTO APPOINTMENTS VALUES(5,'Pam','Poovey','2022-06-22','T10:00:00','new Patient',1);
INSERT INTO APPOINTMENTS VALUES(6,'Chewie','Poovey','2022-06-22','T10:30:00','new Patient',2);
